[package]
name = "ferriskey-api"
description = "FerrisKey API"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
ferriskey-core = { path = "../core", features=["utoipa_support"] }
anyhow = "1.0.97"
axum = "0.8.1"
axum-cookie = "0.2.3"
axum-extra = { version = "0.10.0", features = [
    "typed-header",
] }
axum-macros = "0.5.0"
axum-server = { version = "0.7.2", features = ["tls-rustls"] }
base64 = "0.22.1"
chrono = { version = "0.4.40", features = ["serde"] }
clap = { version = "4.5.32", features = ["derive", "env"] }
dotenv = "0.15.0"
regex = "1.11.1"
rustls = { version = "0.23.31" }
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }
tower-http = { version = "0.6.2", features = ["cors", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
utoipa = { version = "5.3.1", features = ["chrono", "uuid"] }
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }
uuid = { version = "1.16.0", features = ["serde", "v4", "v7"] }
validator = { version = "0.20.0", features = ["derive"] }
base32 = "0.5.1"
axum-prometheus = "0.9.0"
url = "2.5.4"
utoipa-scalar = { version = "0.3.0", features = ["axum"] }

[dev-dependencies]
test-context = "*"
axum-test = "*"
sea-orm = { version = "1.1.14", features = ["sqlx-postgres"] }
